% Basic class for Ashoka CSP homework
%
%
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{ashoka-crypto}
              [2024/09/08 - v1.0
 Standard class for CS-1306/MAT-1201 homework]

\LoadClass[12pt]{article}
\RequirePackage{ashoka-crypto}

\typeout{}
\typeout{*** Document Class 'ashoka-crypto' for Ashoka Cryptography CS-1306/MAT-1201 homework}
\typeout{*** Bugs/comments/suggestions/technicalities via Google Classroom.}
\typeout{}
